name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
        node-version: [16.x]

    uses: ./.github/workflows/tests.yml
    with:
      os: ${{ matrix.os }}
      node-version: ${{ matrix.node-version }}
