name: Tests

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      node-version:
        required: true
        type: string

jobs:
  build-test:
    name: Build and test
    runs-on: ${{ inputs.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: "npm"

      - run: npm install --immutable

      - name: Test
        run: npm run test
